version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: farhanisrakyen.com/php
        container_name: app
        tty: true
        restart: unless-stopped
        environment:
            XDEBUG_CONFIG: remote_autostart=1 remote_enable=1 remote_port=9001 remote_host=host.docker.internal
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www/html/
        volumes:
            - ./:/var/www/html/
            - ./docker/php/laravel.ini:/usr/local/etc/php/conf.d/laravel.ini
        networks:
            - app-network

    db:
        image: mysql:8.0
        ports:
            - 3306:3306
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        volumes:
            - db-data:/var/lib/mysql/
            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - app-network

    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www/html/
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network
#Docker Networks
networks:
    app-network:
        driver: bridge

#Volumes
volumes:
    db-data: ~
